# Generated by Django 4.2.4 on 2025-06-09 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_exp', models.IntegerField()),
                ('as_nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Expressions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.JSONField()),
                ('operateur_arithmetique', models.CharField(choices=[('+', '+'), ('-', '-'), ('*', '*'), ('/', '/'), ('%', '%')], max_length=50)),
                ('id_precedente', models.IntegerField(blank=True, null=True)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expression_action', to='restitutions.actions')),
            ],
        ),
        migrations.CreateModel(
            name='Restitutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restitutions_crees', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restitutions_modifiees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cond', models.IntegerField(null=True)),
                ('id_action', models.IntegerField()),
                ('restitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='restitutions.restitutions')),
            ],
        ),
        migrations.CreateModel(
            name='Jointures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference1', models.JSONField()),
                ('reference2', models.JSONField()),
                ('type', models.CharField(choices=[('LEFT', 'LEFT'), ('RIGHT', 'RIGHT'), ('INNER', 'INNER'), ('FULL', 'FULL')], max_length=10)),
                ('code_format1', models.IntegerField(null=True)),
                ('code_format2', models.IntegerField(null=True)),
                ('restitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jointures', to='restitutions.restitutions')),
            ],
        ),
        migrations.CreateModel(
            name='Formats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_structure', models.IntegerField()),
                ('restitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='restitutions.restitutions')),
            ],
        ),
        migrations.CreateModel(
            name='Fonctions_calculs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('sum', 'sum'), ('min', 'min'), ('max', 'max'), ('avg', 'avg'), ('med', 'med'), ('mod', 'mod'), ('ecart', 'ecart'), ('var', 'var'), ('qp', 'qp'), ('tc', 'tc')], max_length=50, null=True)),
                ('expression', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fonction_expression', to='restitutions.expressions')),
            ],
        ),
        migrations.CreateModel(
            name='Filtre_populations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur_logique', models.CharField(choices=[('OU', 'OU'), ('ET', 'ET')], max_length=50)),
                ('champs_cible', models.CharField(max_length=255)),
                ('operateur_comparaison', models.CharField(choices=[('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('=', '='), ('!=', '!='), ('%', '%')], max_length=5)),
                ('parametre', models.JSONField()),
                ('id_anterieure', models.IntegerField(blank=True, null=True)),
                ('restitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filtres', to='restitutions.restitutions')),
            ],
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_logique', models.CharField(choices=[('SI', 'SI'), ('SINON SI', 'SINON SI'), ('SINON', 'SINON')], max_length=8)),
                ('champs_cible', models.CharField(max_length=255)),
                ('operateur_comparaison', models.CharField(choices=[('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('=', '='), ('!=', '≠')], max_length=5)),
                ('valeur_reference', models.CharField(max_length=255)),
                ('operateur_logique', models.CharField(choices=[('OU', 'OU'), ('ET', 'ET')], max_length=5)),
                ('id_precedente', models.IntegerField(blank=True, null=True)),
                ('id_anterieure', models.IntegerField(blank=True, null=True)),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_operation', to='restitutions.operations')),
            ],
        ),
        migrations.CreateModel(
            name='Clause_regroupement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('champs_cible', models.CharField(max_length=255)),
                ('restitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause_regroupement', to='restitutions.restitutions')),
            ],
        ),
        migrations.CreateModel(
            name='Champs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('transformation', models.CharField(blank=True, max_length=255, null=True)),
                ('taille', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('separateur', models.CharField(blank=True, max_length=255, null=True)),
                ('parametre', models.JSONField()),
                ('restitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='champs', to='restitutions.restitutions')),
            ],
        ),
        migrations.CreateModel(
            name='Affichages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Bâton', 'Bâton'), ('Circulaire', 'Circulaire'), ('Camembert', 'Camembert'), ('Cercle', 'Cercle'), ('Ligne', 'Ligne'), ('Histogramme', 'Histogramme'), ('Tableau croisée dynamique', 'Tableau croisée dynamique'), ('Tableau simple', 'Tableau simple')], max_length=255)),
                ('type', models.CharField(choices=[('Cartographique', 'Cartographique'), ('Graphique', 'Graphique'), ('Tableau', 'Tableau')], max_length=100)),
                ('restitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affichages', to='restitutions.restitutions')),
            ],
        ),
        migrations.AddField(
            model_name='actions',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='restitutions.operations'),
        ),
    ]
