# Generated by Django 4.2.4 on 2025-06-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='as_nom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='champs',
            name='parametre',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='operateur_logique',
            field=models.CharField(choices=[('OU', 'OU'), ('ET', 'ET')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='expressions',
            name='operateur_arithmetique',
            field=models.CharField(choices=[('+', '+'), ('-', '-'), ('*', '*'), ('/', '/'), ('%', '%')], max_length=50, null=True),
        ),
    ]
