# Generated by Django 4.2.4 on 2025-06-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0002_alter_actions_as_nom_alter_champs_parametre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='id_exp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='operateur_logique',
            field=models.CharField(choices=[('ET', 'ET'), ('OU', 'OU')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='filtre_populations',
            name='operateur_logique',
            field=models.CharField(choices=[('ET', 'ET'), ('OU', 'OU')], max_length=50),
        ),
        migrations.AlterField(
            model_name='operations',
            name='id_action',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operations',
            name='id_cond',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
