# Generated by Django 4.2.4 on 2025-06-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0003_alter_actions_id_exp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='id_exp',
        ),
    ]
