# Generated by Django 4.2.4 on 2025-06-10 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0004_remove_actions_id_exp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fonctions_calculs',
            old_name='operation',
            new_name='nom_fonction',
        ),
        migrations.RemoveField(
            model_name='expressions',
            name='action',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='id_action',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='id_cond',
        ),
        migrations.AddField(
            model_name='expressions',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expression_operation', to='restitutions.operations'),
        ),
        migrations.AddField(
            model_name='operations',
            name='as_nom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='operateur_logique',
            field=models.CharField(choices=[('OU', 'OU'), ('ET', 'ET')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='filtre_populations',
            name='operateur_logique',
            field=models.CharField(choices=[('OU', 'OU'), ('ET', 'ET')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Actions',
        ),
    ]
