# Generated by Django 4.2.4 on 2025-06-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0005_rename_operation_fonctions_calculs_nom_fonction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='operateur_logique',
            field=models.CharField(choices=[('ET', 'ET'), ('OU', 'OU')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='expressions',
            name='operateur_arithmetique',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='filtre_populations',
            name='operateur_logique',
            field=models.CharField(choices=[('ET', 'ET'), ('OU', 'OU')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Fonctions_calculs',
        ),
    ]
