# Generated by Django 4.2.4 on 2025-06-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0006_alter_conditions_operateur_logique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='operateur_logique',
            field=models.CharField(choices=[('OU', 'OU'), ('ET', 'ET')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='expressions',
            name='valeur',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='filtre_populations',
            name='operateur_logique',
            field=models.CharField(choices=[('OU', 'OU'), ('ET', 'ET')], max_length=50),
        ),
    ]
