# Generated by Django 4.2.4 on 2025-06-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0007_alter_conditions_operateur_logique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtre_populations',
            name='operateur_logique',
            field=models.CharField(choices=[('OU', 'OU'), ('ET', 'ET')], max_length=50, null=True),
        ),
    ]
