# Generated by Django 4.2.4 on 2025-06-16 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0008_alter_filtre_populations_operateur_logique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clause_regroupement',
            name='restitution',
        ),
        migrations.RemoveField(
            model_name='clause_regroupement',
            name='type',
        ),
        migrations.AddField(
            model_name='clause_regroupement',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clauses_regroupement_operation', to='restitutions.operations'),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='operateur_logique',
            field=models.CharField(choices=[('ET', 'ET'), ('OU', 'OU')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='filtre_populations',
            name='operateur_logique',
            field=models.CharField(choices=[('ET', 'ET'), ('OU', 'OU')], max_length=50, null=True),
        ),
    ]
