# Generated by Django 4.2.4 on 2025-06-16 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0009_remove_clause_regroupement_restitution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='operateur_logique',
            field=models.CharField(choices=[('OU', 'OU'), ('ET', 'ET')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='filtre_populations',
            name='operateur_logique',
            field=models.CharField(choices=[('OU', 'OU'), ('ET', 'ET')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filtre_populations',
            name='restitution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filtres_pop', to='restitutions.restitutions'),
        ),
        migrations.AlterField(
            model_name='formats',
            name='restitution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formats_selected', to='restitutions.restitutions'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='restitution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_selected', to='restitutions.restitutions'),
        ),
    ]
