# Generated by Django 4.2.4 on 2025-06-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0010_alter_conditions_operateur_logique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affichages',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='affichages',
            name='type',
        ),
        migrations.AddField(
            model_name='affichages',
            name='nom_affichage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='operateur_logique',
            field=models.CharField(choices=[('ET', 'ET'), ('OU', 'OU')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='filtre_populations',
            name='operateur_logique',
            field=models.CharField(choices=[('ET', 'ET'), ('OU', 'OU')], max_length=50, null=True),
        ),
    ]
