# Generated by Django 4.2.4 on 2025-06-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0011_remove_affichages_nom_remove_affichages_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointures',
            name='type',
            field=models.CharField(choices=[('LJ', 'LEFT JOIN'), ('RJ', 'RIGHT JOIN'), ('IJ', 'INNER JOIN'), ('FJ', 'FULL JOIN')], max_length=10),
        ),
    ]
