# Generated by Django 4.2.4 on 2025-06-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0012_alter_jointures_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='champs',
            name='as_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='champs',
            name='parametre',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='champs',
            name='transformation',
            field=models.CharField(blank=True, choices=[('op_', 'op_'), ('none', 'none'), ('concat', 'concat'), ('extract', 'extract'), ('AxesX', 'AxesX'), ('AxesY', 'AxesY'), ('maps', 'maps')], max_length=50, null=True),
        ),
    ]
