# Generated by Django 4.2.4 on 2025-06-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0013_champs_as_nom_alter_champs_parametre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champs',
            name='parametre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='champs',
            name='separateur',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='champs',
            name='transformation',
            field=models.CharField(choices=[('op_', 'op_'), ('none', 'none'), ('concat', 'concat'), ('extract', 'extract'), ('AxesX', 'AxesX'), ('AxesY', 'AxesY'), ('maps', 'maps')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='operateur_logique',
            field=models.CharField(choices=[('OU', 'OU'), ('ET', 'ET')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='filtre_populations',
            name='operateur_logique',
            field=models.CharField(choices=[('OU', 'OU'), ('ET', 'ET')], max_length=50, null=True),
        ),
    ]
