# Generated by Django 4.2.4 on 2025-06-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0015_alter_clause_regroupement_operation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditions',
            name='champs_cible',
        ),
        migrations.AlterField(
            model_name='conditions',
            name='cle_logique',
            field=models.CharField(choices=[('si', 'si'), ('sinon si', 'sinon si'), ('sinon', 'sinon')], max_length=8),
        ),
        migrations.RemoveField(
            model_name='conditions',
            name='valeur_reference',
        ),
        migrations.AddField(
            model_name='conditions',
            name='champs_cible',
            field=models.ManyToManyField(related_name='cible_conditions', to='restitutions.expressions'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='valeur_reference',
            field=models.ManyToManyField(related_name='valeur_conditions', to='restitutions.expressions'),
        ),
    ]
