# Generated by Django 4.2.4 on 2025-06-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0016_remove_conditions_champs_cible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='champs_cible',
            field=models.ManyToManyField(blank=True, null=True, related_name='cible_conditions', to='restitutions.expressions'),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='operateur_comparaison',
            field=models.CharField(blank=True, choices=[('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('=', '='), ('!=', '≠')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='valeur_reference',
            field=models.ManyToManyField(blank=True, null=True, related_name='valeur_conditions', to='restitutions.expressions'),
        ),
    ]
