# Generated by Django 4.2.4 on 2025-06-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0017_alter_conditions_champs_cible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champs',
            name='transformation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
