# Generated by Django 4.2.4 on 2025-06-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0018_alter_champs_transformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='champs',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
