# Generated by Django 4.2.4 on 2025-06-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0020_alter_conditions_operateur_comparaison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause_regroupement',
            name='id_precedente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='operateur_logique',
            field=models.CharField(choices=[('ET', 'ET'), ('OU', 'OU')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='filtre_populations',
            name='operateur_logique',
            field=models.CharField(choices=[('ET', 'ET'), ('OU', 'OU')], max_length=50, null=True),
        ),
    ]
