# Generated by Django 4.2.4 on 2025-06-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0022_alter_conditions_operateur_logique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditions',
            name='id_anterieure',
        ),
        migrations.RemoveField(
            model_name='filtre_populations',
            name='id_anterieure',
        ),
    ]
