# Generated by Django 4.2.4 on 2025-07-18 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0023_remove_conditions_id_anterieure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clause_regroupement',
            name='operation',
        ),
        migrations.AddField(
            model_name='clause_regroupement',
            name='expression',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause_regroupement', to='restitutions.expressions'),
        ),
    ]
