# Generated by Django 4.2.4 on 2025-07-18 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0024_remove_clause_regroupement_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clause_regroupement',
            name='champs_cible',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clause_regroupement',
            name='expression',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause_regroupement', to='restitutions.expressions'),
        ),
    ]
