# Generated by Django 4.2.4 on 2025-07-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0025_alter_clause_regroupement_champs_cible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champs',
            name='transformation',
        ),
        migrations.RemoveField(
            model_name='champs',
            name='type',
        ),
        migrations.AddField(
            model_name='filtre_populations',
            name='id_precedente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
