# Generated by Django 4.2.4 on 2025-07-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0026_remove_champs_transformation_remove_champs_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='champs',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
