# Generated by Django 4.2.4 on 2025-07-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0027_champs_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='operateur_comparaison',
            field=models.CharField(blank=True, choices=[('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('==', '=='), ('!=', '≠'), ('%', '%')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='operateur_logique',
            field=models.CharField(choices=[('ET', 'ET'), ('OU', 'OU')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='filtre_populations',
            name='operateur_logique',
            field=models.CharField(choices=[('ET', 'ET'), ('OU', 'OU')], max_length=50, null=True),
        ),
    ]
