# Generated by Django 4.2.4 on 2025-07-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0028_alter_conditions_operateur_comparaison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formats',
            name='name_structure',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='operateur_logique',
            field=models.CharField(choices=[('OU', 'OU'), ('ET', 'ET')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='filtre_populations',
            name='operateur_logique',
            field=models.CharField(choices=[('OU', 'OU'), ('ET', 'ET')], max_length=50, null=True),
        ),
    ]
