# Generated by Django 4.2.4 on 2025-07-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0029_formats_name_structure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='champs',
            name='typeAttribut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
