# Generated by Django 4.2.4 on 2025-07-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0031_alter_champs_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
