# Generated by Django 4.2.4 on 2025-07-31 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0032_operations_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operations',
            name='nom',
        ),
    ]
