# Generated by Django 4.2.4 on 2025-08-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0033_remove_operations_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='champs_cible',
            field=models.ManyToManyField(blank=True, related_name='cible_conditions', to='restitutions.expressions'),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='operateur_logique',
            field=models.CharField(choices=[('ET', 'ET'), ('OU', 'OU')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='valeur_reference',
            field=models.ManyToManyField(blank=True, related_name='valeur_conditions', to='restitutions.expressions'),
        ),
        migrations.AlterField(
            model_name='filtre_populations',
            name='operateur_logique',
            field=models.CharField(choices=[('ET', 'ET'), ('OU', 'OU')], max_length=50, null=True),
        ),
    ]
